version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.4.0
  python: circleci/python@4.0.0
filters: &tagged
  tags:
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)([-+].*)?$/
  branches:
    ignore: /.*/
jobs:
  build_install_collection_test:
    executor: collection-testing/python
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - collection-testing/build_install_collection:
          path: "buildinstall-test/"
          install: true
          ansible_galaxy_executable: uv run ansible-galaxy
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - build_install_collection_test
      - collection-testing/pytest
      - collection-testing/antsibull_docs
      - collection-testing/pre_commit_lint:
          requirements-file: requirements.txt
      - orb-tools/pack:
          filters: *tagged
      - collection-testing/publish_github:
          filters: *tagged
          context:
            - collection-publishing
      - collection-testing/publish_galaxy:
          filters: *tagged
          context:
            - collection-publishing
      - orb-tools/publish:
          orb_name: maxhoesel-ansible/ansible-collection-testing
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - build_install_collection-test
            - collection-testing/antsibull_docs
            - collection-testing/pre_commit_lint
            - collection-testing/publish_github
            - collection-testing/publish_galaxy
          context:
            - orb-publishing
          filters: *tagged
