version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.4.0
  python: circleci/python@4.0.0

filters: &tagged
  tags:
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)([-+].*)?$/
  branches:
    ignore: /.*/

jobs:
  build-install-collection-test:
    executor: collection-testing/python
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - collection-testing/build-install-collection:
          path: "buildinstall-test/"
          install: true
          ansible_galaxy_executable: uv run ansible-galaxy

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - build-install-collection-test
      - collection-testing/pytest
      - collection-testing/antsibull-docs
      - collection-testing/pre-commit-lint:
          requirements-file: requirements.txt

      - orb-tools/pack:
          filters: *tagged
          requires:
            - build-install-collection-test
            - collection-testing/antsibull-docs
            - collection-testing/pre-commit-lint
      - collection-testing/publish-github:
          filters: *tagged
          context:
            - collection-publishing
      - collection-testing/publish-galaxy:
          filters: *tagged
          context:
            - collection-publishing

      - orb-tools/publish:
          orb_name: maxhoesel-ansible/ansible-collection-testing
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - collection-testing/publish-github
            - collection-testing/publish-galaxy
          context:
            - orb-publishing
          filters: *tagged
