version: 2.1
orbs:
  collection-testing: maxhoesel-ansible/ansible-collection-testing@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &tagged
  tags:
    # Official Semver Regex. Yes, it's LOOOONG
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  branches:
    ignore: /.*/

jobs:
  podman-test:
    executor: collection-testing/default
    steps:
      - checkout
      - collection-testing/install-podman-on-ubuntu
      - run:
          command: podman info
  requirements-txt-test:
    executor: collection-testing/default
    steps:
      - checkout
      - collection-testing/install-requirements-txt:
          file: requirements.txt
      - run:
          command: ansible --version
  build-install-collection-test:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - checkout
      - collection-testing/install-requirements-txt:
          file: requirements.txt
      - collection-testing/build-install-collection:
          path: "buildinstall-test/"
          install: true

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - podman-test
      - requirements-txt-test
      - build-install-collection-test
      - collection-testing/antsibull-docs
      - collection-testing/pre-commit-lint:
          requirements-file: requirements.txt
      - collection-testing/run-tox-environments:
          resource-class: large
          retries: 2
          retry-delay: 60
      - orb-tools/pack:
          filters: *tagged
      - collection-testing/publish-github:
          filters: *tagged
          context:
            - collection-publishing
      - collection-testing/publish-galaxy:
          filters: *tagged
          context:
            - collection-publishing
      - orb-tools/publish:
          orb-name: maxhoesel-ansible/ansible-collection-testing
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - podman-test
            - requirements-txt-test
            - build-install-collection-test
            - collection-testing/antsibull-docs
            - collection-testing/pre-commit-lint
            - collection-testing/run-tox-environments
            - collection-testing/publish-github
            - collection-testing/publish-galaxy
          context:
            - orb-publishing
          filters: *tagged
