description: >
  Run a set of tox scenarios based on a filter and utilizing parallelization.
  Can be used with tox-ansible to test roles effectively.
parameters:
  match-environments:
    description: Run environments that contain this string expression
    type: string
    default: "ansible"
  ignore-environments:
    description: Ignore environments that contain this string expression
    type: string
    default: "lint"
  parallelism:
    description: Split role tests across this number of executors
    type: integer
    default: 1
  resource-class:
    description: Set the executor resource class. Can be any of the machine resource classes.
    type: enum
    default: medium
    enum: ["medium", "large", "xlarge", "2xlarge"]
  retries:
    description: Number of times to retry the scenario tests before giving up.
    type: integer
    default: 1
  retry-delay:
    description: Wait for this number of seconds between failed test runs.
    type: integer
    default: 60
machine:
  image: ubuntu-2204:current
  docker_layer_caching: false
resource_class: <<parameters.resource-class>>
parallelism: <<parameters.parallelism>>
steps:
  - checkout
  - install-podman-on-ubuntu
  - install-requirements-txt
  - run:
      name: Run Tox Scenario
      command: <<include(scripts/tox-test.sh)>>
      environment:
        TOX_ENVIRONMENTS: <<parameters.match-environments>>
        TOX_IGNORE: <<parameters.ignore-environments>>
        TEST_RETRIES: <<parameters.retries>>
        TEST_RETRY_DELAY: <<parameters.retry-delay>>
